version: "3"
services:
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./database/pqdb/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  backend:
    restart: always
    build:
      context: "./"
    env_file:
      - "/.env"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
